version: "3.8"
services:
  nats_network:
    container_name: nat-gateway
    image: nats
    ports:
      - 4222:4222
    # networks:
    #   - nats_network
  gateway:
    container_name: gateway-container
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on:
      - nats_network
    env_file:
      - ./gateway/.env
    environment:
      - DATA_BASE_URL=${DATA_BASE_URL}
      - ENVIRONMENT=${ENVIRONMENT}
      - NATS_URL_LIVE=${NATS_URL_LIVE}
      - NATS_URL_LOCAL=${NATS_URL_LOCAL}
    ports:
      - 5000:5000
    # networks:
    #   - nats_network

  user:
    container_name: user-container
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      - nats_network
    env_file:
      - ./user/.env
    environment:
      - DATA_BASE_URL=${DATA_BASE_URL}
      - ENVIRONMENT=${ENVIRONMENT}
      - NATS_URL_LIVE=${NATS_URL_LIVE}
      - NATS_URL_LOCAL=${NATS_URL_LOCAL}
    # networks:
    #   - nats_network
  product:
    container_name: product-container
    build:
      context: ./product
      dockerfile: Dockerfile
    depends_on:
      - nats_network
    env_file:
      - ./user/.env
    environment:
      - DATA_BASE_URL=${DATA_BASE_URL}
      - ENVIRONMENT=${ENVIRONMENT}
      - NATS_URL_LIVE=${NATS_URL_LIVE}
      - NATS_URL_LOCAL=${NATS_URL_LOCAL}
    # networks:
    #   - nats_network

# networks:
#   nats_network:
#     name: nats_network
#     driver: bridge

