version: "3.8"
services:
  nats:
    image: nats
    ports:
      - 4222:4222
  gateway:
    container_name: gateway-container
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on:
      - nats
    env_file:
      - ./gateway/.env
    ports:
      - "5000:5000"

  user:
    container_name: user-container
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      - nats
    env_file:
      - ./user/.env
    # ports:
    #   - "${USER_PORT}:${USER_PORT}"
  product:
    container_name: product-container
    build:
      context: ./product
      dockerfile: Dockerfile
    depends_on:
      - nats
    env_file:
      - ./user/.env
    # ports:
    #   - "${USER_PORT}:${USER_PORT}"
