services:
  mongodb:
    image: mongo:latest
    container_name: ${CONTAINER_PREFIX}mongodb
    ports:
      - "27017:27017"
    volumes:
      - ${DATA_PATH}/mongodb:/data/db
      - ${CONFIG_PATH}/mongodb:/etc/mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=badhon118
      - MONGO_INITDB_DATABASE=html
      - TZ=${TZ}
    restart: ${RESTART_POLICY}
